<?php

namespace Database\Seeders;

use App\Models\OutreachSite;
use Illuminate\Database\Seeder;

class OutreachSitesSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            // Malir District
            ['district' => 'Malir', 'union_council' => 'Ibrahim Hydri', 'fix_site' => 'PHCC Cattle Colony', 'outreach_site' => 'Aziz Abad', 'coordinates' => '24.857408,67.135619', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ibrahim Hydri', 'fix_site' => 'PHCC Cattle Colony', 'outreach_site' => 'Haji Alam Goth', 'coordinates' => '24.862428,67.141489', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ibrahim Hydri', 'fix_site' => 'PHCC Cattle Colony', 'outreach_site' => 'Cattle Colony', 'coordinates' => '24.870378,67.131879', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ibrahim Hydri', 'fix_site' => 'PHCC Cattle Colony', 'outreach_site' => 'Bhains Colony', 'coordinates' => '24.861788,67.122789', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ibrahim Hydri', 'fix_site' => 'PHCC Rehri', 'outreach_site' => 'Rehri Goth', 'coordinates' => '24.846758,67.130619', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ibrahim Hydri', 'fix_site' => 'PHCC Rehri', 'outreach_site' => 'Shams Abad', 'coordinates' => '24.851388,67.139789', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ibrahim Hydri', 'fix_site' => 'PHCC Rehri', 'outreach_site' => 'Essa Nagri', 'coordinates' => '24.853768,67.145919', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Memon Goth', 'fix_site' => 'BHU Memon Goth', 'outreach_site' => 'Memon Goth', 'coordinates' => '24.873588,67.156439', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Memon Goth', 'fix_site' => 'BHU Memon Goth', 'outreach_site' => 'Yousuf Goth', 'coordinates' => '24.878228,67.149789', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Memon Goth', 'fix_site' => 'BHU Memon Goth', 'outreach_site' => 'Ali Muhammad Goth', 'coordinates' => '24.881168,67.161549', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Murad Memon', 'fix_site' => 'PHCC Murad Memon', 'outreach_site' => 'Murad Memon Goth', 'coordinates' => '24.885828,67.170719', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Murad Memon', 'fix_site' => 'PHCC Murad Memon', 'outreach_site' => 'Haji Mureed Goth', 'coordinates' => '24.890468,67.163969', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Murad Memon', 'fix_site' => 'PHCC Murad Memon', 'outreach_site' => 'Ghulam Hussain Goth', 'coordinates' => '24.893408,67.175729', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ghaggar Phatak', 'fix_site' => 'BHU Ghaggar', 'outreach_site' => 'Ghaggar Goth', 'coordinates' => '24.900258,67.182379', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ghaggar Phatak', 'fix_site' => 'BHU Ghaggar', 'outreach_site' => 'Phatak Area', 'coordinates' => '24.904898,67.175629', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Ghaggar Phatak', 'fix_site' => 'BHU Ghaggar', 'outreach_site' => 'Khamiso Goth', 'coordinates' => '24.907838,67.187389', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Model Colony', 'fix_site' => 'RHC Model Colony', 'outreach_site' => 'Model Colony Sector A', 'coordinates' => '24.912478,67.194039', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Model Colony', 'fix_site' => 'RHC Model Colony', 'outreach_site' => 'Model Colony Sector B', 'coordinates' => '24.917118,67.187289', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Model Colony', 'fix_site' => 'RHC Model Colony', 'outreach_site' => 'Model Colony Sector C', 'coordinates' => '24.920058,67.199049', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Model Colony', 'fix_site' => 'RHC Model Colony', 'outreach_site' => 'Model Colony Sector D', 'coordinates' => '24.924698,67.192299', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Kala Board', 'fix_site' => 'PHCC Kala Board', 'outreach_site' => 'Kala Board', 'coordinates' => '24.929338,67.205709', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Kala Board', 'fix_site' => 'PHCC Kala Board', 'outreach_site' => 'Saudabad', 'coordinates' => '24.933978,67.198959', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Kala Board', 'fix_site' => 'PHCC Kala Board', 'outreach_site' => 'Qayyumabad', 'coordinates' => '24.936918,67.210719', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Shah Faisal', 'fix_site' => 'PHCC Shah Faisal', 'outreach_site' => 'Shah Faisal Colony 1', 'coordinates' => '24.872108,67.102349', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Shah Faisal', 'fix_site' => 'PHCC Shah Faisal', 'outreach_site' => 'Shah Faisal Colony 2', 'coordinates' => '24.876748,67.095599', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Shah Faisal', 'fix_site' => 'PHCC Shah Faisal', 'outreach_site' => 'Shah Faisal Colony 3', 'coordinates' => '24.879688,67.107359', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Landhi', 'fix_site' => 'RHC Landhi', 'outreach_site' => 'Landhi 1', 'coordinates' => '24.884328,67.114009', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Landhi', 'fix_site' => 'RHC Landhi', 'outreach_site' => 'Landhi 2', 'coordinates' => '24.888968,67.107259', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Landhi', 'fix_site' => 'RHC Landhi', 'outreach_site' => 'Landhi 3', 'coordinates' => '24.891908,67.119019', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Landhi', 'fix_site' => 'RHC Landhi', 'outreach_site' => 'Landhi 4', 'coordinates' => '24.896548,67.112269', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Korangi', 'fix_site' => 'PHCC Korangi', 'outreach_site' => 'Korangi 1', 'coordinates' => '24.829828,67.130609', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Korangi', 'fix_site' => 'PHCC Korangi', 'outreach_site' => 'Korangi 2', 'coordinates' => '24.834468,67.123859', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Korangi', 'fix_site' => 'PHCC Korangi', 'outreach_site' => 'Korangi 3', 'coordinates' => '24.837408,67.135619', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Korangi', 'fix_site' => 'PHCC Korangi', 'outreach_site' => 'Korangi 4', 'coordinates' => '24.842048,67.128869', 'comments' => null],
            ['district' => 'Malir', 'union_council' => 'Korangi', 'fix_site' => 'PHCC Korangi', 'outreach_site' => 'Korangi 5', 'coordinates' => '24.844988,67.140629', 'comments' => null],

            // East District
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 1', 'coordinates' => '24.922348,67.092179', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 2', 'coordinates' => '24.926988,67.085429', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 3', 'coordinates' => '24.929928,67.097189', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 4', 'coordinates' => '24.934568,67.090439', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 5', 'coordinates' => '24.937508,67.102199', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 6', 'coordinates' => '24.942148,67.095449', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 7', 'coordinates' => '24.945088,67.107209', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 10', 'coordinates' => '24.949728,67.100459', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 11', 'coordinates' => '24.952668,67.112219', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 13', 'coordinates' => '24.957308,67.105469', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulshan-e-Iqbal', 'fix_site' => 'PHCC Gulshan', 'outreach_site' => 'Gulshan Block 14', 'coordinates' => '24.960248,67.117229', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulzar-e-Hijri', 'fix_site' => 'BHU Gulzar-e-Hijri', 'outreach_site' => 'Gulzar-e-Hijri Sector A', 'coordinates' => '24.964888,67.110479', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulzar-e-Hijri', 'fix_site' => 'BHU Gulzar-e-Hijri', 'outreach_site' => 'Gulzar-e-Hijri Sector B', 'coordinates' => '24.967828,67.122239', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulzar-e-Hijri', 'fix_site' => 'BHU Gulzar-e-Hijri', 'outreach_site' => 'Gulzar-e-Hijri Sector C', 'coordinates' => '24.972468,67.115489', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Gulzar-e-Hijri', 'fix_site' => 'BHU Gulzar-e-Hijri', 'outreach_site' => 'Gulzar-e-Hijri Sector D', 'coordinates' => '24.975408,67.127249', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Scheme 33', 'fix_site' => 'PHCC Scheme 33', 'outreach_site' => 'Scheme 33 Sector 1', 'coordinates' => '24.980048,67.120499', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Scheme 33', 'fix_site' => 'PHCC Scheme 33', 'outreach_site' => 'Scheme 33 Sector 2', 'coordinates' => '24.982988,67.132259', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Scheme 33', 'fix_site' => 'PHCC Scheme 33', 'outreach_site' => 'Scheme 33 Sector 3', 'coordinates' => '24.987628,67.125509', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Scheme 33', 'fix_site' => 'PHCC Scheme 33', 'outreach_site' => 'Scheme 33 Sector 4', 'coordinates' => '24.990568,67.137269', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Jamshed Town', 'fix_site' => 'RHC Jamshed Town', 'outreach_site' => 'PECHS Block 1', 'coordinates' => '24.878208,67.052519', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Jamshed Town', 'fix_site' => 'RHC Jamshed Town', 'outreach_site' => 'PECHS Block 2', 'coordinates' => '24.882848,67.045769', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Jamshed Town', 'fix_site' => 'RHC Jamshed Town', 'outreach_site' => 'PECHS Block 3', 'coordinates' => '24.885788,67.057529', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Jamshed Town', 'fix_site' => 'RHC Jamshed Town', 'outreach_site' => 'PECHS Block 6', 'coordinates' => '24.890428,67.050779', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Jamshed Town', 'fix_site' => 'RHC Jamshed Town', 'outreach_site' => 'Bahadurabad', 'coordinates' => '24.893368,67.062539', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Ferozabad', 'fix_site' => 'BHU Ferozabad', 'outreach_site' => 'Ferozabad Sector A', 'coordinates' => '24.898008,67.055789', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Ferozabad', 'fix_site' => 'BHU Ferozabad', 'outreach_site' => 'Ferozabad Sector B', 'coordinates' => '24.900948,67.067549', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Ferozabad', 'fix_site' => 'BHU Ferozabad', 'outreach_site' => 'Ferozabad Sector C', 'coordinates' => '24.905588,67.060799', 'comments' => null],
            ['district' => 'East', 'union_council' => 'Ferozabad', 'fix_site' => 'BHU Ferozabad', 'outreach_site' => 'Ferozabad Sector D', 'coordinates' => '24.908528,67.072559', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block A', 'coordinates' => '24.950168,67.035809', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block B', 'coordinates' => '24.954808,67.029059', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block C', 'coordinates' => '24.957748,67.040819', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block D', 'coordinates' => '24.962388,67.034069', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block E', 'coordinates' => '24.965328,67.045829', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block F', 'coordinates' => '24.969968,67.039079', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block G', 'coordinates' => '24.972908,67.050839', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block H', 'coordinates' => '24.977548,67.044089', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block I', 'coordinates' => '24.980488,67.055849', 'comments' => null],
            ['district' => 'East', 'union_council' => 'North Nazimabad', 'fix_site' => 'PHCC North Nazimabad', 'outreach_site' => 'North Nazimabad Block J', 'coordinates' => '24.985128,67.049099', 'comments' => null],

            // West District
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 1', 'coordinates' => '24.955168,66.978149', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 2', 'coordinates' => '24.959808,66.971399', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 3', 'coordinates' => '24.962748,66.983159', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 4', 'coordinates' => '24.967388,66.976409', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 5', 'coordinates' => '24.970328,66.988169', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 6', 'coordinates' => '24.974968,66.981419', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 7', 'coordinates' => '24.977908,66.993179', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 8', 'coordinates' => '24.982548,66.986429', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 9', 'coordinates' => '24.985488,66.998189', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 10', 'coordinates' => '24.990128,66.991439', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 11', 'coordinates' => '24.993068,67.003199', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Orangi', 'fix_site' => 'RHC Orangi Town', 'outreach_site' => 'Orangi Town Sector 12', 'coordinates' => '24.997708,66.996449', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Manghopir', 'fix_site' => 'PHCC Manghopir', 'outreach_site' => 'Manghopir Goth', 'coordinates' => '25.002348,67.008209', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Manghopir', 'fix_site' => 'PHCC Manghopir', 'outreach_site' => 'Dhobi Ghat', 'coordinates' => '25.006988,67.001459', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Manghopir', 'fix_site' => 'PHCC Manghopir', 'outreach_site' => 'Shrine Area', 'coordinates' => '25.009928,67.013219', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Manghopir', 'fix_site' => 'PHCC Manghopir', 'outreach_site' => 'Gadap Road', 'coordinates' => '25.014568,67.006469', 'comments' => null],
            ['district' => 'West', 'union_council' => 'SITE', 'fix_site' => 'BHU SITE Area', 'outreach_site' => 'SITE Industrial Area A', 'coordinates' => '24.905508,67.018229', 'comments' => null],
            ['district' => 'West', 'union_council' => 'SITE', 'fix_site' => 'BHU SITE Area', 'outreach_site' => 'SITE Industrial Area B', 'coordinates' => '24.910148,67.011479', 'comments' => null],
            ['district' => 'West', 'union_council' => 'SITE', 'fix_site' => 'BHU SITE Area', 'outreach_site' => 'SITE Industrial Area C', 'coordinates' => '24.913088,67.023239', 'comments' => null],
            ['district' => 'West', 'union_council' => 'SITE', 'fix_site' => 'BHU SITE Area', 'outreach_site' => 'Haroonabad', 'coordinates' => '24.917728,67.016489', 'comments' => null],
            ['district' => 'West', 'union_council' => 'SITE', 'fix_site' => 'BHU SITE Area', 'outreach_site' => 'Metroville', 'coordinates' => '24.920668,67.028249', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Baldia', 'fix_site' => 'RHC Baldia Town', 'outreach_site' => 'Baldia Sector 1', 'coordinates' => '24.887308,66.968499', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Baldia', 'fix_site' => 'RHC Baldia Town', 'outreach_site' => 'Baldia Sector 2', 'coordinates' => '24.891948,66.961749', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Baldia', 'fix_site' => 'RHC Baldia Town', 'outreach_site' => 'Baldia Sector 3', 'coordinates' => '24.894888,66.973509', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Baldia', 'fix_site' => 'RHC Baldia Town', 'outreach_site' => 'Baldia Sector 4', 'coordinates' => '24.899528,66.966759', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Baldia', 'fix_site' => 'RHC Baldia Town', 'outreach_site' => 'Baldia Sector 5', 'coordinates' => '24.902468,66.978519', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Baldia', 'fix_site' => 'RHC Baldia Town', 'outreach_site' => 'Ittehad Town', 'coordinates' => '24.907108,66.971769', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Baldia', 'fix_site' => 'RHC Baldia Town', 'outreach_site' => 'Saeedabad', 'coordinates' => '24.910048,66.983529', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Mominabad', 'fix_site' => 'PHCC Mominabad', 'outreach_site' => 'Mominabad Sector A', 'coordinates' => '24.925308,66.993779', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Mominabad', 'fix_site' => 'PHCC Mominabad', 'outreach_site' => 'Mominabad Sector B', 'coordinates' => '24.929948,66.987029', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Mominabad', 'fix_site' => 'PHCC Mominabad', 'outreach_site' => 'Mominabad Sector C', 'coordinates' => '24.932888,66.998789', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Mominabad', 'fix_site' => 'PHCC Mominabad', 'outreach_site' => 'Muslim Mianwali Colony', 'coordinates' => '24.937528,66.992039', 'comments' => null],
            ['district' => 'West', 'union_council' => 'Mominabad', 'fix_site' => 'PHCC Mominabad', 'outreach_site' => 'Qasba Colony', 'coordinates' => '24.940468,67.003799', 'comments' => null],

            // Keamari District
            ['district' => 'Keamari', 'union_council' => 'Mauripur', 'fix_site' => 'BHU Mauripur', 'outreach_site' => 'Mauripur Goth', 'coordinates' => '24.855988,66.958149', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Mauripur', 'fix_site' => 'BHU Mauripur', 'outreach_site' => 'Hawks Bay', 'coordinates' => '24.860628,66.951399', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Mauripur', 'fix_site' => 'BHU Mauripur', 'outreach_site' => 'Sandspit', 'coordinates' => '24.863568,66.963159', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Mauripur', 'fix_site' => 'BHU Mauripur', 'outreach_site' => 'Fishermen Colony', 'coordinates' => '24.868208,66.956409', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Shershah', 'fix_site' => 'PHCC Shershah', 'outreach_site' => 'Shershah Kabari Market', 'coordinates' => '24.873148,66.968169', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Shershah', 'fix_site' => 'PHCC Shershah', 'outreach_site' => 'Scrap Market Area', 'coordinates' => '24.877788,66.961419', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Shershah', 'fix_site' => 'PHCC Shershah', 'outreach_site' => 'Transport Area', 'coordinates' => '24.880728,66.973179', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Lyari', 'fix_site' => 'RHC Lyari', 'outreach_site' => 'Lyari Sector 1', 'coordinates' => '24.858368,66.998429', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Lyari', 'fix_site' => 'RHC Lyari', 'outreach_site' => 'Lyari Sector 2', 'coordinates' => '24.863008,66.991679', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Lyari', 'fix_site' => 'RHC Lyari', 'outreach_site' => 'Lyari Sector 3', 'coordinates' => '24.865948,67.003439', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Lyari', 'fix_site' => 'RHC Lyari', 'outreach_site' => 'Chakiwara', 'coordinates' => '24.870588,66.996689', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Lyari', 'fix_site' => 'RHC Lyari', 'outreach_site' => 'Agra Taj Colony', 'coordinates' => '24.873528,67.008449', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Lyari', 'fix_site' => 'RHC Lyari', 'outreach_site' => 'Kalakot', 'coordinates' => '24.878168,67.001699', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Lyari', 'fix_site' => 'RHC Lyari', 'outreach_site' => 'Bihar Colony', 'coordinates' => '24.881108,67.013459', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Lyari', 'fix_site' => 'RHC Lyari', 'outreach_site' => 'Baghdadi', 'coordinates' => '24.885748,67.006709', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Kemari', 'fix_site' => 'PHCC Kemari', 'outreach_site' => 'Kemari Town', 'coordinates' => '24.825688,66.978469', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Kemari', 'fix_site' => 'PHCC Kemari', 'outreach_site' => 'Port Area', 'coordinates' => '24.830328,66.971719', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Kemari', 'fix_site' => 'PHCC Kemari', 'outreach_site' => 'Baba Bhit Island', 'coordinates' => '24.833268,66.983479', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Kemari', 'fix_site' => 'PHCC Kemari', 'outreach_site' => 'Manora', 'coordinates' => '24.837908,66.976729', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Banaras', 'fix_site' => 'BHU Banaras', 'outreach_site' => 'Banaras Colony', 'coordinates' => '24.892848,66.988489', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Banaras', 'fix_site' => 'BHU Banaras', 'outreach_site' => 'Khadda Market', 'coordinates' => '24.897488,66.981739', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Banaras', 'fix_site' => 'BHU Banaras', 'outreach_site' => 'Nai Abadi', 'coordinates' => '24.900428,66.993499', 'comments' => null],
            ['district' => 'Keamari', 'union_council' => 'Banaras', 'fix_site' => 'BHU Banaras', 'outreach_site' => 'PIB Colony', 'coordinates' => '24.905068,66.986749', 'comments' => null],
        ];

        foreach ($sites as $site) {
            OutreachSite::create($site);
        }
    }
}
