<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\OutreachSite;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class OutreachSiteController extends Controller
{
    /**
     * Get all outreach sites with optional filtering
     */
    public function index(Request $request): JsonResponse
    {
        $query = OutreachSite::query();

        if ($request->has('district')) {
            $query->where('district', $request->district);
        }

        if ($request->has('union_council')) {
            $query->where('union_council', $request->union_council);
        }

        if ($request->has('fix_site')) {
            $query->where('fix_site', $request->fix_site);
        }

        return response()->json($query->get());
    }

    /**
     * Get distinct districts
     */
    public function districts(): JsonResponse
    {
        $districts = OutreachSite::distinct()
            ->orderBy('district')
            ->pluck('district');

        return response()->json($districts);
    }

    /**
     * Get union councils (towns) for a district
     */
    public function unionCouncils(Request $request): JsonResponse
    {
        $query = OutreachSite::distinct();

        if ($request->has('district')) {
            $query->where('district', $request->district);
        }

        $ucs = $query->orderBy('union_council')->pluck('union_council');

        return response()->json($ucs);
    }

    /**
     * Get fix sites for a district/UC
     */
    public function fixSites(Request $request): JsonResponse
    {
        $query = OutreachSite::distinct();

        if ($request->has('district')) {
            $query->where('district', $request->district);
        }

        if ($request->has('union_council')) {
            $query->where('union_council', $request->union_council);
        }

        $sites = $query->orderBy('fix_site')->pluck('fix_site');

        return response()->json($sites);
    }

    /**
     * Get outreach sites for a fix site
     */
    public function outreachSites(Request $request): JsonResponse
    {
        $query = OutreachSite::query();

        if ($request->has('district')) {
            $query->where('district', $request->district);
        }

        if ($request->has('union_council')) {
            $query->where('union_council', $request->union_council);
        }

        if ($request->has('fix_site')) {
            $query->where('fix_site', $request->fix_site);
        }

        $sites = $query->orderBy('outreach_site')
            ->get(['id', 'outreach_site', 'coordinates']);

        return response()->json($sites);
    }

    /**
     * Store a new outreach site (uses hash-based duplicate detection)
     */
    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'district' => 'required|string',
            'union_council' => 'required|string',
            'fix_site' => 'required|string',
            'outreach_site' => 'required|string',
            'coordinates' => 'nullable|string',
            'comments' => 'nullable|string',
        ]);

        // Generate hash for duplicate detection
        $locationHash = md5(
            strtolower(trim($validated['district'])) . '|' .
            strtolower(trim($validated['union_council'])) . '|' .
            strtolower(trim($validated['fix_site'])) . '|' .
            strtolower(trim($validated['outreach_site']))
        );

        // Check if site already exists using hash
        $existingSite = OutreachSite::where('location_hash', $locationHash)->first();

        if ($existingSite) {
            return response()->json([
                'message' => 'Outreach site already exists',
                'data' => $existingSite,
                'created' => false,
            ], 200);
        }

        // Create new site (hash will be auto-generated by model)
        $site = OutreachSite::create([
            'district' => $validated['district'],
            'union_council' => $validated['union_council'],
            'fix_site' => $validated['fix_site'],
            'outreach_site' => $validated['outreach_site'],
            'coordinates' => $validated['coordinates'] ?? null,
            'comments' => $validated['comments'] ?? null,
        ]);

        return response()->json([
            'message' => 'Outreach site created successfully',
            'data' => $site,
            'created' => true,
        ], 201);
    }
}
