<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BridgingTheGap;
use App\Models\ChildLineList;
use App\Models\FgdsCommunity;
use App\Models\FgdsHealthWorkers;
use App\Models\OutreachSite;
use App\Models\VaccinationRecord;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

/**
 * Fixed Site Report
 *
 * A single consolidated report for one fixed (vaccination) site: the user picks a
 * Union Council, then one of its fixed sites, and every related record — FGDs
 * (community + health workers), Bridging the Gap sessions with action plans,
 * vaccination records and the child line list — is shown on one page and can be
 * exported to a multi-sheet Excel workbook.
 *
 * Notes on the data model:
 *  - `outreach_sites` is the catalogue that maps district -> union_council ->
 *    fix_site -> outreach_site. It is the only place fixed sites are enumerated.
 *  - FGDs-Community, Bridging the Gap and Vaccination Records carry a `fix_site`
 *    column, so they are filtered exactly to the selected fixed site.
 *  - Child Line List has no `fix_site` column; it is linked through its
 *    `outreach` value against the outreach sites that belong to the fixed site.
 *  - FGDs-Health Workers are recorded per health facility (`hfs`) and have no
 *    fixed-site link, so they are shown at UC level (clearly labelled).
 */
class FixedSiteReportController extends Controller
{
    /**
     * Render the report page. Without `uc`/`fix_site` it only shows the pickers.
     */
    public function index(Request $request)
    {
        $unionCouncils = $this->unionCouncils();

        $selectedUc = trim((string) $request->query('uc', ''));
        if ($selectedUc !== '' && ! $unionCouncils->contains($selectedUc)) {
            $selectedUc = '';
        }

        $fixSites = $selectedUc !== '' ? $this->fixSitesForUc($selectedUc) : collect();

        $selectedFixSite = trim((string) $request->query('fix_site', ''));
        if ($selectedFixSite !== '' && ! $fixSites->contains($selectedFixSite)) {
            $selectedFixSite = '';
        }

        $report = ($selectedUc !== '' && $selectedFixSite !== '')
            ? $this->buildReport($selectedUc, $selectedFixSite)
            : null;

        return view('admin.reports.fixed-site', [
            'unionCouncils'   => $unionCouncils,
            'fixSites'        => $fixSites,
            'selectedUc'      => $selectedUc,
            'selectedFixSite' => $selectedFixSite,
            'report'          => $report,
        ]);
    }

    /**
     * Export the whole report for a fixed site as a multi-sheet .xlsx workbook.
     */
    public function export(Request $request)
    {
        $uc = trim((string) $request->query('uc', ''));
        $fixSite = trim((string) $request->query('fix_site', ''));

        if ($uc === '' || $fixSite === '' || ! $this->unionCouncils()->contains($uc)) {
            return redirect()->route('admin.reports.fixed-site')
                ->with('error', 'Select a Union Council and a fixed site before exporting.');
        }
        if (! $this->fixSitesForUc($uc)->contains($fixSite)) {
            return redirect()->route('admin.reports.fixed-site', ['uc' => $uc])
                ->with('error', 'The selected fixed site is not valid for this Union Council.');
        }

        $report = $this->buildReport($uc, $fixSite);

        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setTitle('Fixed Site Report')
            ->setSubject($uc . ' / ' . $fixSite)
            ->setCreator(auth()->user()->name ?? 'Admin');

        $index = 0;

        // --- Summary ---------------------------------------------------------
        $s = $report['summary'];
        $this->writeSheet($spreadsheet, $index++, 'Summary', ['Field', 'Value'], [
            ['Report', 'Fixed Site Report'],
            ['Union Council', $uc],
            ['Fixed Site', $fixSite],
            ['District', $report['district'] ?? '—'],
            ['Outreach sites under this fixed site', $report['outreach_sites'] ? implode(', ', $report['outreach_sites']) : '—'],
            ['Generated at', now()->format('M d, Y H:i')],
            ['Generated by', auth()->user()->name ?? 'Admin'],
            ['', ''],
            ['FGDs-Community sessions', $s['fgds_community']],
            ['FGDs-Community barriers', $s['fgds_community_barriers']],
            ['FGDs-Health Workers sessions (UC level)', $s['fgds_health_workers']],
            ['FGDs-Health Workers barriers', $s['fgds_health_workers_barriers']],
            ['Bridging the Gap sessions', $s['bridging']],
            ['Bridging the Gap action plans', $s['action_plans']],
            ['Bridging the Gap IIT members', $s['iit_members']],
            ['Vaccination records', $s['vaccination']],
            ['Vaccination records (vaccinated)', $s['vaccinated']],
            ['Child line list children', $s['child_line_list']],
        ]);

        // --- FGDs-Community --------------------------------------------------
        $this->writeSheet($spreadsheet, $index++, 'FGD-Community',
            ['Form ID', 'Date', 'Venue', 'District', 'UC', 'Fixed Site', 'Outreach', 'Community',
                'Males', 'Females', 'Total', 'Barriers', 'Facilitator (TKF)', 'Submitted By', 'Created'],
            $report['fgds_community']->map(fn ($r) => [
                $r->unique_id,
                optional($r->date)->format('Y-m-d'),
                $r->venue,
                $r->district,
                $r->uc,
                $r->fix_site,
                $r->outreach,
                is_array($r->community) ? implode(', ', $r->community) : $r->community,
                $r->participants_males,
                $r->participants_females,
                (int) $r->participants_males + (int) $r->participants_females,
                $r->barriers->count(),
                $r->facilitator_tkf,
                $r->user->name ?? '—',
                optional($r->created_at)->format('Y-m-d'),
            ])->all());

        $this->writeSheet($spreadsheet, $index++, 'FGD-Community Barriers',
            ['Form ID', 'Date', 'Venue', 'Category', 'Sr. No', 'Barrier'],
            $report['fgds_community']->flatMap(fn ($r) => $r->barriers->map(fn ($b) => [
                $r->unique_id,
                optional($r->date)->format('Y-m-d'),
                $r->venue,
                $b->category->name ?? 'Uncategorized',
                $b->serial_number,
                $b->barrier_text,
            ]))->all());

        // --- FGDs-Health Workers --------------------------------------------
        $this->writeSheet($spreadsheet, $index++, 'FGD-Health Workers',
            ['Form ID', 'Date', 'Health Facility (HFS)', 'Address', 'UC',
                'Males', 'Females', 'Total', 'Barriers', 'Facilitator (TKF)', 'Submitted By', 'Created'],
            $report['fgds_health_workers']->map(fn ($r) => [
                $r->unique_id,
                optional($r->date)->format('Y-m-d'),
                $r->hfs,
                $r->address,
                $r->uc,
                $r->participants_males,
                $r->participants_females,
                (int) $r->participants_males + (int) $r->participants_females,
                $r->barriers->count(),
                $r->facilitator_tkf,
                $r->user->name ?? '—',
                optional($r->created_at)->format('Y-m-d'),
            ])->all());

        $this->writeSheet($spreadsheet, $index++, 'FGD-HW Barriers',
            ['Form ID', 'Health Facility (HFS)', 'Category', 'Sr. No', 'Barrier'],
            $report['fgds_health_workers']->flatMap(fn ($r) => $r->barriers->map(fn ($b) => [
                $r->unique_id,
                $r->hfs,
                $b->category->name ?? 'Uncategorized',
                $b->serial_number,
                $b->barrier_text,
            ]))->all());

        // --- Bridging the Gap -----------------------------------------------
        $this->writeSheet($spreadsheet, $index++, 'Bridging the Gap',
            ['Form ID', 'Date', 'Venue', 'District', 'UC', 'Fixed Site',
                'Males', 'Females', 'Total', 'Attendance', 'IIT Members', 'Action Plans', 'Submitted By', 'Created'],
            $report['bridging']->map(fn ($r) => [
                $r->unique_id,
                optional($r->date)->format('Y-m-d'),
                $r->venue,
                $r->district,
                $r->uc,
                $r->fix_site,
                $r->participants_males,
                $r->participants_females,
                (int) $r->participants_males + (int) $r->participants_females,
                $r->participants->count(),
                $r->teamMembers->count(),
                $r->actionPlans->count(),
                $r->user->name ?? '—',
                optional($r->created_at)->format('Y-m-d'),
            ])->all());

        $this->writeSheet($spreadsheet, $index++, 'BTG Action Plans',
            ['Form ID', 'Sr. No', 'Problem', 'Solution', 'Action Needed', 'Responsible', 'Timeline'],
            $report['bridging']->flatMap(fn ($r) => $r->actionPlans->map(fn ($p) => [
                $r->unique_id,
                $p->serial_number,
                $p->problem,
                $p->solution,
                $p->action_needed,
                $p->who_is_responsible,
                $p->timeline,
            ]))->all());

        $this->writeSheet($spreadsheet, $index++, 'BTG IIT Members',
            ['Form ID', 'Name', 'Designation', 'Contact', 'CNIC', 'Gender', 'Source'],
            $report['bridging']->flatMap(fn ($r) => $r->teamMembers->map(fn ($m) => [
                $r->unique_id,
                $m->participant->name ?? '—',
                $m->participant->designation ?? $m->participant->title_designation ?? '—',
                $m->participant->contact_no ?? '—',
                $m->participant->cnic ?? '—',
                $m->participant->gender ?? '—',
                $m->source_type,
            ]))->all());

        // --- Vaccination Records --------------------------------------------
        $this->writeSheet($spreadsheet, $index++, 'Vaccination Records',
            ['Form ID', 'Sr. No', 'UC', 'Fixed Site', 'District', 'Child Name', 'Father Name', 'Age',
                'Address', 'Contact', 'Category', 'Vaccinated', 'Date of Vaccination',
                'Community Member', 'CM Contact', 'Submitted By', 'Created'],
            $report['vaccination']->map(fn ($r) => [
                $r->unique_id,
                $r->serial_number,
                $r->uc,
                $r->fix_site,
                $r->district,
                $r->child_name,
                $r->father_name,
                $r->age,
                $r->address,
                $r->contact_number,
                $r->category,
                $r->vaccinated,
                optional($r->date_of_vaccination)->format('Y-m-d'),
                $r->community_member_name,
                $r->community_member_contact,
                $r->user->name ?? '—',
                optional($r->created_at)->format('Y-m-d'),
            ])->all());

        // --- Child Line List ------------------------------------------------
        $this->writeSheet($spreadsheet, $index++, 'Child Line List',
            ['Form ID', 'Division', 'District', 'Town', 'UC', 'Outreach', 'Child Name', 'Father Name',
                'Gender', 'DOB', 'Age (months)', 'Vaccinator', 'IIT Member', 'IIT Contact', 'Father CNIC',
                'House #', 'Address', 'Phone', 'Type', 'Missed Vaccines', 'Reasons', 'Plan for Coverage',
                'Date of Coverage', 'Created'],
            $report['child_line_list']->map(fn ($r) => [
                $r->unique_id,
                $r->division,
                $r->district,
                $r->town,
                $r->uc,
                $r->outreach,
                $r->child_name,
                $r->father_name,
                ucfirst((string) $r->gender),
                optional($r->date_of_birth)->format('Y-m-d'),
                $r->age_in_months,
                $r->vaccinator_name,
                $r->iit_member_name,
                $r->iit_member_contact,
                $r->father_cnic,
                $r->house_number,
                $r->address,
                $r->guardian_phone,
                $r->type,
                is_array($r->missed_vaccines) ? implode(', ', $r->missed_vaccines) : $r->missed_vaccines,
                $r->reasons_of_missing,
                $r->plan_for_coverage,
                optional($r->date_of_coverage)->format('Y-m-d'),
                optional($r->created_at)->format('Y-m-d'),
            ])->all());

        $spreadsheet->setActiveSheetIndex(0);

        $filename = 'fixed-site-report_' . Str::slug($uc . ' ' . $fixSite) . '_' . date('Y-m-d') . '.xlsx';
        $writer = new Xlsx($spreadsheet);

        return response()->streamDownload(function () use ($writer) {
            $writer->save('php://output');
        }, $filename, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ]);
    }

    /* ===================================================================== *
     *  Data gathering
     * ===================================================================== */

    /**
     * Pull every record tied to the given UC + fixed site into one structure.
     */
    private function buildReport(string $uc, string $fixSite): array
    {
        $variants = $this->ucVariants($uc);
        $outreachNames = $this->outreachSitesFor($uc, $fixSite);

        // FGDs-Community — site-specific (has a fix_site column).
        $fgdsCommunity = FgdsCommunity::with(['barriers.category', 'participants', 'user'])
            ->whereIn('uc', $variants)
            ->where('fix_site', $fixSite)
            ->orderByDesc('date')
            ->get();

        // FGDs-Health Workers — UC level (no fix_site / outreach link in schema).
        $fgdsHealthWorkers = FgdsHealthWorkers::with(['barriers.category', 'participants', 'user'])
            ->whereIn('uc', $variants)
            ->orderByDesc('date')
            ->get();

        // Bridging the Gap — site-specific (has a fix_site column).
        $bridging = BridgingTheGap::with(['participants', 'teamMembers.participant', 'actionPlans', 'user'])
            ->whereIn('uc', $variants)
            ->where('fix_site', $fixSite)
            ->orderByDesc('date')
            ->get();

        // Vaccination Records — site-specific (has a fix_site column).
        $vaccination = VaccinationRecord::with('user')
            ->whereIn('uc', $variants)
            ->where('fix_site', $fixSite)
            ->orderBy('serial_number')
            ->orderByDesc('created_at')
            ->get();

        // Child Line List — linked through its outreach site to the fixed site.
        $cllQuery = ChildLineList::with('user')->whereIn('uc', $variants);
        $cllSiteSpecific = false;
        if (! empty($outreachNames)) {
            $cllSiteSpecific = true;
            $cllQuery->where(function ($q) use ($outreachNames, $fixSite) {
                $q->whereIn('outreach', $outreachNames)
                    ->orWhere('outreach', $fixSite);
            });
        }
        $childLineList = $cllQuery->orderByDesc('created_at')->get();

        return [
            'uc'                  => $uc,
            'fix_site'            => $fixSite,
            'district'            => OutreachSite::where('union_council', $uc)
                ->where('fix_site', $fixSite)->value('district'),
            'outreach_sites'      => $outreachNames,
            'fgds_community'      => $fgdsCommunity,
            'fgds_health_workers' => $fgdsHealthWorkers,
            'bridging'            => $bridging,
            'vaccination'         => $vaccination,
            'child_line_list'     => $childLineList,
            'cll_site_specific'   => $cllSiteSpecific,
            'summary'             => [
                'fgds_community'           => $fgdsCommunity->count(),
                'fgds_community_barriers'  => $fgdsCommunity->sum(fn ($r) => $r->barriers->count()),
                'fgds_health_workers'      => $fgdsHealthWorkers->count(),
                'fgds_health_workers_barriers' => $fgdsHealthWorkers->sum(fn ($r) => $r->barriers->count()),
                'bridging'                 => $bridging->count(),
                'action_plans'             => $bridging->sum(fn ($r) => $r->actionPlans->count()),
                'iit_members'              => $bridging->sum(fn ($r) => $r->teamMembers->count()),
                'vaccination'              => $vaccination->count(),
                'vaccinated'               => $vaccination->where('vaccinated', 'YES')->count(),
                'child_line_list'          => $childLineList->count(),
            ],
        ];
    }

    /* ===================================================================== *
     *  Lookups
     * ===================================================================== */

    /** Distinct Union Councils from the outreach-site catalogue. */
    private function unionCouncils()
    {
        return OutreachSite::query()
            ->whereNotNull('union_council')
            ->where('union_council', '!=', '')
            ->pluck('union_council')
            ->map(fn ($v) => trim((string) $v))
            ->filter()
            ->unique()
            ->sort(SORT_NATURAL | SORT_FLAG_CASE)
            ->values();
    }

    /** Distinct fixed sites belonging to a Union Council. */
    private function fixSitesForUc(string $uc)
    {
        return OutreachSite::query()
            ->where('union_council', $uc)
            ->whereNotNull('fix_site')
            ->where('fix_site', '!=', '')
            ->pluck('fix_site')
            ->map(fn ($v) => trim((string) $v))
            ->filter()
            ->unique()
            ->sort(SORT_NATURAL | SORT_FLAG_CASE)
            ->values();
    }

    /** Outreach-site names that sit under a given fixed site. */
    private function outreachSitesFor(string $uc, string $fixSite): array
    {
        return OutreachSite::query()
            ->where('union_council', $uc)
            ->where('fix_site', $fixSite)
            ->whereNotNull('outreach_site')
            ->where('outreach_site', '!=', '')
            ->pluck('outreach_site')
            ->map(fn ($v) => trim((string) $v))
            ->filter()
            ->unique()
            ->values()
            ->all();
    }

    /**
     * Resolve the spelling variants a UC may appear under in the form tables.
     * Form data uses many inconsistent spellings; DashboardController keeps the
     * canonical consolidation map, so we reuse it here.
     */
    private function ucVariants(string $uc): array
    {
        $consolidated = DashboardController::getConsolidatedUcName($uc);
        $variants = DashboardController::getUcVariants($consolidated);

        return array_values(array_unique(array_filter(
            array_merge([$uc, $consolidated], $variants)
        )));
    }

    /* ===================================================================== *
     *  Excel helpers
     * ===================================================================== */

    /**
     * Write a single worksheet from a header row and an array of data rows.
     * All cells are written as strings so codes (CNIC, phone) keep their format.
     */
    private function writeSheet(Spreadsheet $spreadsheet, int $index, string $title, array $headers, array $rows): void
    {
        $sheet = $index === 0 ? $spreadsheet->getActiveSheet() : $spreadsheet->createSheet();
        $sheet->setTitle(Str::limit($title, 31, ''));

        $colCount = count($headers);

        foreach ($headers as $i => $header) {
            $sheet->setCellValueExplicit(
                Coordinate::stringFromColumnIndex($i + 1) . '1',
                $header,
                DataType::TYPE_STRING
            );
        }

        $rowNum = 2;
        foreach ($rows as $row) {
            $col = 1;
            foreach ($row as $value) {
                $sheet->setCellValueExplicit(
                    Coordinate::stringFromColumnIndex($col) . $rowNum,
                    $value === null ? '' : (string) $value,
                    DataType::TYPE_STRING
                );
                $col++;
            }
            $rowNum++;
        }

        if ($colCount > 0) {
            $lastCol = Coordinate::stringFromColumnIndex($colCount);
            $headerStyle = $sheet->getStyle('A1:' . $lastCol . '1');
            $headerStyle->getFont()->setBold(true)->getColor()->setRGB('FFFFFF');
            $headerStyle->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('047857');
            $sheet->freezePane('A2');
            $sheet->setAutoFilter('A1:' . $lastCol . '1');

            for ($c = 1; $c <= $colCount; $c++) {
                $sheet->getColumnDimensionByColumn($c)->setAutoSize(true);
            }
        }

        if (empty($rows)) {
            $sheet->setCellValue('A2', 'No records for this fixed site.');
        }

        $sheet->setSelectedCell('A1');
    }
}
