<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\Concerns\ReportsSupport;
use App\Http\Controllers\Controller;
use App\Models\BarrierCategory;
use App\Models\BridgingTheGap;
use App\Models\ChildLineList;
use App\Models\FgdsCommunity;
use App\Models\FgdsHealthWorkers;
use App\Models\VaccinationRecord;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

/**
 * Reports hub.
 *
 * One place for every program report. The hub (index) lists the available
 * reports; each report has a filtered on-page view plus an Excel export. The
 * Fixed Site Report keeps its own controller (FixedSiteReportController) and is
 * surfaced here as one of the cards.
 *
 * All reports share the same filter vocabulary — date range (on submission
 * date), district and Union Council — resolved by resolveFilters() and applied
 * through applyFilters(). UC matching goes through the canonical variant list
 * (see ReportsSupport::ucVariants) so inconsistent spellings still aggregate.
 */
class ReportsController extends Controller
{
    use ReportsSupport;

    /* ===================================================================== *
     *  Hub
     * ===================================================================== */

    public function index()
    {
        return view('admin.reports.index', [
            'totals' => [
                'fgds_community'      => FgdsCommunity::count(),
                'fgds_health_workers' => FgdsHealthWorkers::count(),
                'bridging'            => BridgingTheGap::count(),
                'vaccination'         => VaccinationRecord::count(),
                'child_line_list'     => ChildLineList::count(),
            ],
        ]);
    }

    /* ===================================================================== *
     *  Program Summary
     * ===================================================================== */

    public function summary(Request $request)
    {
        $filters = $this->resolveFilters($request);

        return view('admin.reports.summary', array_merge(
            $this->filterOptions($filters),
            [
                'filters' => $filters,
                'report'  => $this->buildSummary($filters),
            ]
        ));
    }

    public function summaryExport(Request $request)
    {
        $filters = $this->resolveFilters($request);
        $data = $this->buildSummary($filters);
        $s = $data['summary'];

        $spreadsheet = $this->newReportSpreadsheet('Program Summary Report', $this->filterSubject($filters));
        $i = 0;

        $this->writeSheet($spreadsheet, $i++, 'Summary', ['Field', 'Value'], [
            ['Report', 'Program Summary Report'],
            ['District', $filters['district'] ?: 'All districts'],
            ['Union Council', $filters['uc'] ?: 'All union councils'],
            ['Date from', $filters['from'] ?: '—'],
            ['Date to', $filters['to'] ?: '—'],
            ['Generated at', now()->format('M d, Y H:i')],
            ['Generated by', auth()->user()->name ?? 'Admin'],
            ['', ''],
            ['FGDs-Community sessions', $s['fgds_community']],
            ['FGDs-Community participants', $s['fgds_community_participants']],
            ['FGDs-Community barriers', $s['fgds_community_barriers']],
            ['FGDs-Health Workers sessions', $s['fgds_health_workers']],
            ['FGDs-Health Workers participants', $s['fgds_health_workers_participants']],
            ['FGDs-Health Workers barriers', $s['fgds_health_workers_barriers']],
            ['Bridging the Gap sessions', $s['bridging']],
            ['Bridging the Gap action plans', $s['action_plans']],
            ['Bridging the Gap IIT members', $s['iit_members']],
            ['Vaccination records', $s['vaccination']],
            ['Vaccination records (vaccinated)', $s['vaccinated']],
            ['Child line list children', $s['child_line_list']],
            ['Child line list (zero dose)', $s['zero_dose']],
            ['Child line list (defaulter)', $s['defaulter']],
        ]);

        $this->writeSheet($spreadsheet, $i++, 'By Union Council',
            ['Union Council', 'FGD-Community', 'FGD-Health Workers', 'Bridging the Gap', 'Vaccination', 'Child Line List'],
            collect($data['by_uc'])->map(fn ($r) => [
                $r['uc'], $r['fgds_community'], $r['fgds_health_workers'], $r['bridging'], $r['vaccination'], $r['child_line_list'],
            ])->all(),
            'No records for the selected filters.');

        $this->writeSheet($spreadsheet, $i++, 'Barriers by Category',
            ['Category', 'Community', 'Health Workers', 'Total'],
            collect($data['barriers_by_category'])->map(fn ($r) => [
                $r['name'], $r['community'], $r['health_workers'], $r['total'],
            ])->all());

        $filename = 'program-summary_' . date('Y-m-d') . '.xlsx';

        return $this->streamWorkbook($spreadsheet, $filename);
    }

    /* ===================================================================== *
     *  Barriers
     * ===================================================================== */

    public function barriers(Request $request)
    {
        $filters = $this->resolveFilters($request);
        $scope = $this->resolveScope($request);

        return view('admin.reports.barriers', array_merge(
            $this->filterOptions($filters),
            [
                'filters' => $filters,
                'scope'   => $scope,
                'report'  => $this->buildBarriers($filters, $scope),
            ]
        ));
    }

    public function barriersExport(Request $request)
    {
        $filters = $this->resolveFilters($request);
        $scope = $this->resolveScope($request);
        $data = $this->buildBarriers($filters, $scope);

        $spreadsheet = $this->newReportSpreadsheet('Barriers Report', $this->filterSubject($filters));
        $i = 0;

        $this->writeSheet($spreadsheet, $i++, 'By Category',
            ['Category', 'Community', 'Health Workers', 'Total'],
            collect($data['by_category'])->map(fn ($r) => [
                $r['name'], $r['community'], $r['health_workers'], $r['total'],
            ])->all());

        $this->writeSheet($spreadsheet, $i++, 'Barrier Details',
            ['Source', 'Form ID', 'Date', 'UC', 'Location', 'Category', 'Sr. No', 'Barrier'],
            collect($data['details'])->map(fn ($r) => [
                $r['source'], $r['form_id'], $r['date'], $r['uc'], $r['location'], $r['category'], $r['serial'], $r['text'],
            ])->all(),
            'No barriers for the selected filters.');

        $filename = 'barriers-report_' . date('Y-m-d') . '.xlsx';

        return $this->streamWorkbook($spreadsheet, $filename);
    }

    /* ===================================================================== *
     *  Vaccination Coverage
     * ===================================================================== */

    public function vaccination(Request $request)
    {
        $filters = $this->resolveFilters($request);
        $category = trim((string) $request->query('category', ''));
        $vaccinated = trim((string) $request->query('vaccinated', ''));

        return view('admin.reports.vaccination', array_merge(
            $this->filterOptions($filters),
            [
                'filters'    => $filters,
                'category'   => $category,
                'vaccinated' => $vaccinated,
                'categories' => ['Defaulter', 'Refusal', 'Zero Dose'],
                'report'     => $this->buildVaccination($filters, $category, $vaccinated),
            ]
        ));
    }

    public function vaccinationExport(Request $request)
    {
        $filters = $this->resolveFilters($request);
        $category = trim((string) $request->query('category', ''));
        $vaccinated = trim((string) $request->query('vaccinated', ''));
        $data = $this->buildVaccination($filters, $category, $vaccinated);
        $s = $data['summary'];

        $spreadsheet = $this->newReportSpreadsheet('Vaccination Coverage Report', $this->filterSubject($filters));
        $i = 0;

        $this->writeSheet($spreadsheet, $i++, 'Summary', ['Field', 'Value'], [
            ['Report', 'Vaccination Coverage Report'],
            ['District', $filters['district'] ?: 'All districts'],
            ['Union Council', $filters['uc'] ?: 'All union councils'],
            ['Category', $category ?: 'All categories'],
            ['Vaccinated', $vaccinated ?: 'All'],
            ['Date from', $filters['from'] ?: '—'],
            ['Date to', $filters['to'] ?: '—'],
            ['Generated at', now()->format('M d, Y H:i')],
            ['', ''],
            ['Total records', $s['total']],
            ['Vaccinated', $s['vaccinated']],
            ['Not vaccinated', $s['not_vaccinated']],
            ['Coverage %', $s['coverage']],
        ]);

        $this->writeSheet($spreadsheet, $i++, 'By Category',
            ['Category', 'Total', 'Vaccinated', 'Not Vaccinated', 'Coverage %'],
            collect($data['by_category'])->map(fn ($r) => [
                $r['category'], $r['total'], $r['vaccinated'], $r['not_vaccinated'], $r['coverage'],
            ])->all());

        $this->writeSheet($spreadsheet, $i++, 'Records',
            ['Form ID', 'Sr. No', 'UC', 'Fixed Site', 'District', 'Child Name', 'Father Name', 'Age',
                'Contact', 'Category', 'Vaccinated', 'Date of Vaccination', 'Community Member', 'Created'],
            $data['records']->map(fn ($r) => [
                $r->unique_id,
                $r->serial_number,
                $r->uc,
                $r->fix_site,
                $r->district,
                $r->child_name,
                $r->father_name,
                $r->age,
                $r->contact_number,
                $r->category,
                $r->vaccinated,
                optional($r->date_of_vaccination)->format('Y-m-d'),
                $r->community_member_name,
                optional($r->created_at)->format('Y-m-d'),
            ])->all(),
            'No vaccination records for the selected filters.');

        $filename = 'vaccination-coverage_' . date('Y-m-d') . '.xlsx';

        return $this->streamWorkbook($spreadsheet, $filename);
    }

    /* ===================================================================== *
     *  Report builders
     * ===================================================================== */

    private function buildSummary(array $f): array
    {
        $fc = $this->applyFilters(FgdsCommunity::query(), $f)->withCount(['participants', 'barriers'])->get();
        $fh = $this->applyFilters(FgdsHealthWorkers::query(), $f, hasDistrict: false)->withCount(['participants', 'barriers'])->get();
        $btg = $this->applyFilters(BridgingTheGap::query(), $f)->withCount(['participants', 'teamMembers', 'actionPlans'])->get();
        $vac = $this->applyFilters(VaccinationRecord::query(), $f)->get(['id', 'uc', 'vaccinated', 'category']);
        $cll = $this->applyFilters(ChildLineList::query(), $f)->get(['id', 'uc', 'type']);

        return [
            'summary' => [
                'fgds_community'                   => $fc->count(),
                'fgds_community_participants'      => $fc->sum('participants_count'),
                'fgds_community_barriers'          => $fc->sum('barriers_count'),
                'fgds_health_workers'              => $fh->count(),
                'fgds_health_workers_participants' => $fh->sum('participants_count'),
                'fgds_health_workers_barriers'     => $fh->sum('barriers_count'),
                'bridging'                         => $btg->count(),
                'bridging_participants'            => $btg->sum('participants_count'),
                'action_plans'                     => $btg->sum('action_plans_count'),
                'iit_members'                      => $btg->sum('team_members_count'),
                'vaccination'                      => $vac->count(),
                'vaccinated'                       => $vac->where('vaccinated', 'YES')->count(),
                'child_line_list'                  => $cll->count(),
                'zero_dose'                        => $cll->filter(fn ($r) => Str::contains(Str::lower((string) $r->type), 'zero'))->count(),
                'defaulter'                        => $cll->filter(fn ($r) => Str::contains(Str::lower((string) $r->type), 'default'))->count(),
            ],
            'by_uc'                => $this->tallyByUc($fc, $fh, $btg, $vac, $cll),
            'barriers_by_category' => $this->barrierCategoryTotals($fc->pluck('id'), $fh->pluck('id')),
        ];
    }

    private function buildBarriers(array $f, string $scope): array
    {
        $wantCommunity = $scope === 'both' || $scope === 'community';
        $wantHealth = $scope === 'both' || $scope === 'health_workers';

        $community = $wantCommunity
            ? $this->applyFilters(FgdsCommunity::query(), $f)->with('barriers.category')->get()
            : collect();
        $health = $wantHealth
            ? $this->applyFilters(FgdsHealthWorkers::query(), $f, hasDistrict: false)->with('barriers.category')->get()
            : collect();

        // Category totals seeded from the canonical list so every category shows.
        $categories = [];
        foreach (BarrierCategory::CANONICAL as $name) {
            $categories[$name] = ['name' => $name, 'community' => 0, 'health_workers' => 0, 'total' => 0];
        }
        $uncategorized = ['name' => 'Uncategorized', 'community' => 0, 'health_workers' => 0, 'total' => 0];

        $details = [];

        foreach ($community as $r) {
            foreach ($r->barriers as $b) {
                $cat = $b->category->name ?? null;
                $bucket = $cat && isset($categories[$cat]) ? $categories[$cat] : $uncategorized;
                $bucket['community']++;
                $bucket['total']++;
                if ($cat && isset($categories[$cat])) { $categories[$cat] = $bucket; } else { $uncategorized = $bucket; }
                $details[] = [
                    'source' => 'Community', 'form_id' => $r->unique_id,
                    'date' => optional($r->date)->format('Y-m-d'), 'uc' => $r->uc,
                    'location' => $r->venue, 'category' => $cat ?? 'Uncategorized',
                    'serial' => $b->serial_number, 'text' => $b->barrier_text,
                ];
            }
        }

        foreach ($health as $r) {
            foreach ($r->barriers as $b) {
                $cat = $b->category->name ?? null;
                $bucket = $cat && isset($categories[$cat]) ? $categories[$cat] : $uncategorized;
                $bucket['health_workers']++;
                $bucket['total']++;
                if ($cat && isset($categories[$cat])) { $categories[$cat] = $bucket; } else { $uncategorized = $bucket; }
                $details[] = [
                    'source' => 'Health Workers', 'form_id' => $r->unique_id,
                    'date' => optional($r->date)->format('Y-m-d'), 'uc' => $r->uc,
                    'location' => $r->hfs, 'category' => $cat ?? 'Uncategorized',
                    'serial' => $b->serial_number, 'text' => $b->barrier_text,
                ];
            }
        }

        $byCategory = collect($categories)->values();
        if ($uncategorized['total'] > 0) {
            $byCategory->push($uncategorized);
        }
        // Sort most-frequent first, but keep zero-rows in canonical order at the end.
        $byCategory = $byCategory->sortByDesc('total')->values();

        return [
            'by_category' => $byCategory->all(),
            'details'     => $details,
            'totals'      => [
                'sessions'  => $community->count() + $health->count(),
                'community' => $community->count(),
                'health'    => $health->count(),
                'barriers'  => $byCategory->sum('total'),
            ],
        ];
    }

    private function buildVaccination(array $f, string $category, string $vaccinated): array
    {
        $query = $this->applyFilters(VaccinationRecord::query(), $f);
        if ($f['fix_site'] !== '') {
            $query->where('fix_site', $f['fix_site']);
        }
        if ($category !== '') {
            $query->where('category', $category);
        }
        if ($vaccinated !== '') {
            $query->where('vaccinated', $vaccinated);
        }

        $records = $query->with('user')->orderByDesc('created_at')->get();

        $total = $records->count();
        $vac = $records->where('vaccinated', 'YES')->count();
        $notVac = $total - $vac;

        $cats = [];
        foreach (['Defaulter', 'Refusal', 'Zero Dose'] as $c) {
            $rows = $records->where('category', $c);
            $t = $rows->count();
            $v = $rows->where('vaccinated', 'YES')->count();
            $cats[] = [
                'category'       => $c,
                'total'          => $t,
                'vaccinated'     => $v,
                'not_vaccinated' => $t - $v,
                'coverage'       => $t > 0 ? round($v / $t * 100, 1) : 0,
            ];
        }

        return [
            'summary' => [
                'total'          => $total,
                'vaccinated'     => $vac,
                'not_vaccinated' => $notVac,
                'coverage'       => $total > 0 ? round($vac / $total * 100, 1) : 0,
            ],
            'by_category' => $cats,
            'by_uc'       => $this->vaccinationByUc($records),
            'records'     => $records,
        ];
    }

    /* ===================================================================== *
     *  Aggregation helpers
     * ===================================================================== */

    /** Count sessions per consolidated Union Council across all form types. */
    private function tallyByUc($fc, $fh, $btg, $vac, $cll): array
    {
        $rows = [];
        $add = function (string $key, $collection) use (&$rows) {
            foreach ($collection as $item) {
                $uc = DashboardController::getConsolidatedUcName($item->uc) ?: ($item->uc ?: 'Unknown');
                $rows[$uc] ??= ['uc' => $uc, 'fgds_community' => 0, 'fgds_health_workers' => 0, 'bridging' => 0, 'vaccination' => 0, 'child_line_list' => 0];
                $rows[$uc][$key]++;
            }
        };
        $add('fgds_community', $fc);
        $add('fgds_health_workers', $fh);
        $add('bridging', $btg);
        $add('vaccination', $vac);
        $add('child_line_list', $cll);

        ksort($rows, SORT_NATURAL | SORT_FLAG_CASE);

        return array_values($rows);
    }

    private function vaccinationByUc($records): array
    {
        $rows = [];
        foreach ($records as $r) {
            $uc = DashboardController::getConsolidatedUcName($r->uc) ?: ($r->uc ?: 'Unknown');
            $rows[$uc] ??= ['uc' => $uc, 'total' => 0, 'vaccinated' => 0];
            $rows[$uc]['total']++;
            if ($r->vaccinated === 'YES') {
                $rows[$uc]['vaccinated']++;
            }
        }
        ksort($rows, SORT_NATURAL | SORT_FLAG_CASE);

        return array_values($rows);
    }

    /** Barrier counts per canonical category for the given FGD record ids. */
    private function barrierCategoryTotals($communityIds, $healthIds): array
    {
        $categories = [];
        foreach (BarrierCategory::CANONICAL as $name) {
            $categories[$name] = ['name' => $name, 'community' => 0, 'health_workers' => 0, 'total' => 0];
        }
        $uncategorized = ['name' => 'Uncategorized', 'community' => 0, 'health_workers' => 0, 'total' => 0];

        $tally = function ($rows, string $key) use (&$categories, &$uncategorized) {
            foreach ($rows as $row) {
                $name = $row->name ?? null;
                if ($name && isset($categories[$name])) {
                    $categories[$name][$key] += $row->c;
                    $categories[$name]['total'] += $row->c;
                } else {
                    $uncategorized[$key] += $row->c;
                    $uncategorized['total'] += $row->c;
                }
            }
        };

        if ($communityIds->isNotEmpty()) {
            $tally(\App\Models\FgdsCommunityBarrier::query()
                ->whereIn('fgds_community_id', $communityIds)
                ->leftJoin('barrier_categories', 'fgds_community_barriers.barrier_category_id', '=', 'barrier_categories.id')
                ->selectRaw('barrier_categories.name as name, count(*) as c')
                ->groupBy('barrier_categories.name')
                ->get(), 'community');
        }
        if ($healthIds->isNotEmpty()) {
            $tally(\App\Models\FgdsHealthWorkersBarrier::query()
                ->whereIn('fgds_health_workers_id', $healthIds)
                ->leftJoin('barrier_categories', 'fgds_health_workers_barriers.barrier_category_id', '=', 'barrier_categories.id')
                ->selectRaw('barrier_categories.name as name, count(*) as c')
                ->groupBy('barrier_categories.name')
                ->get(), 'health_workers');
        }

        $out = collect($categories)->values();
        if ($uncategorized['total'] > 0) {
            $out->push($uncategorized);
        }

        return $out->sortByDesc('total')->values()->all();
    }

    /* ===================================================================== *
     *  Filters
     * ===================================================================== */

    private function resolveFilters(Request $request): array
    {
        return [
            'from'      => $this->validDate($request->query('from')),
            'to'        => $this->validDate($request->query('to')),
            'district'  => trim((string) $request->query('district', '')),
            'uc'        => trim((string) $request->query('uc', '')),
            'fix_site'  => trim((string) $request->query('fix_site', '')),
        ];
    }

    private function resolveScope(Request $request): string
    {
        $scope = trim((string) $request->query('scope', 'both'));

        return in_array($scope, ['both', 'community', 'health_workers'], true) ? $scope : 'both';
    }

    /**
     * Apply the shared date/district/UC filters to a query. `hasDistrict` is
     * false for FGDs-Health-Workers, which has no district column.
     */
    private function applyFilters(Builder $query, array $f, bool $hasDistrict = true): Builder
    {
        if ($f['from']) {
            $query->whereDate('created_at', '>=', $f['from']);
        }
        if ($f['to']) {
            $query->whereDate('created_at', '<=', $f['to']);
        }
        if ($f['district'] !== '' && $hasDistrict) {
            $query->where('district', $f['district']);
        }
        if ($f['uc'] !== '') {
            $query->whereIn('uc', $this->ucVariants($f['uc']));
        }

        return $query;
    }

    private function validDate($value): ?string
    {
        $value = trim((string) $value);
        if ($value === '') {
            return null;
        }
        try {
            return CarbonImmutable::parse($value)->toDateString();
        } catch (\Throwable) {
            return null;
        }
    }

    /** Dropdown options for the filter bar; fix-site list depends on chosen UC. */
    private function filterOptions(array $filters): array
    {
        return [
            'districts'     => $this->districts(),
            'unionCouncils' => $this->unionCouncils(),
            'fixSites'      => $filters['uc'] !== '' ? $this->fixSitesForUc($filters['uc']) : collect(),
        ];
    }

    private function filterSubject(array $f): string
    {
        $parts = array_filter([
            $f['district'] ?: null,
            $f['uc'] ?: null,
            $f['from'] || $f['to'] ? trim(($f['from'] ?: '…') . ' to ' . ($f['to'] ?: '…')) : null,
        ]);

        return $parts ? implode(' / ', $parts) : 'All records';
    }
}
